version: "v2.28.1-desktop.1"

services:
  db: 
    container_name: db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7531
      - POSTGRES_DB=testify
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  testify-backend:
    container_name: testify-backend
    build: .
    ports:
      - 1014:1014
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
    driver: local
    
